--
-- table creations
--

CREATE TABLE MI182_rrlee.unit_numbers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_number VARCHAR2(10),
    PRIMARY KEY (id),
    UNIQUE (unit_number)
);

CREATE TABLE MI182_rrlee.house_numbers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    house_number VARCHAR2(10),
    PRIMARY KEY (id),
    UNIQUE (house_number)
);

CREATE TABLE MI182_rrlee.street_names (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_name VARCHAR2(50),
    PRIMARY KEY (id),
    UNIQUE (street_name)
);

CREATE TABLE MI182_rrlee.districts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    district VARCHAR2(50),
    PRIMARY KEY (id),
    UNIQUE (district)
);

CREATE TABLE MI182_rrlee.cities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city VARCHAR2(50),
    PRIMARY KEY (id),
    UNIQUE (city)
);

CREATE TABLE MI182_rrlee.postal_codes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    postal_code VARCHAR2(10),
    PRIMARY KEY (id),
    UNIQUE (postal_code)
);

CREATE TABLE MI182_rrlee.provinces (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    province VARCHAR2(10),
    PRIMARY KEY (id),
    UNIQUE (province)
);

CREATE TABLE MI182_rrlee.countries (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country VARCHAR2(10),
    PRIMARY KEY (id),
    UNIQUE (country)
);

CREATE TABLE MI182_rrlee.presidents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    middle_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    unit_number NUMBER,
    house_number NUMBER,
    street_name NUMBER,
    district NUMBER,
    city NUMBER,
    postal_code NUMBER,
    province NUMBER,
    country NUMBER,
    contact_number VARCHAR2(15),
    email_address VARCHAR2(100),
    PRIMARY KEY (id),
    UNIQUE (contact_number, email_address),
    FOREIGN KEY (unit_number) REFERENCES MI182_rrlee.unit_numbers (id),
    FOREIGN KEY (house_number) REFERENCES MI182_rrlee.house_numbers (id),
    FOREIGN KEY (street_name) REFERENCES MI182_rrlee.street_names (id),
    FOREIGN KEY (district) REFERENCES MI182_rrlee.districts (id),
    FOREIGN KEY (city) REFERENCES MI182_rrlee.cities (id),
    FOREIGN KEY (postal_code) REFERENCES MI182_rrlee.postal_codes (id),
    FOREIGN KEY (province) REFERENCES MI182_rrlee.provinces (id),
    FOREIGN KEY (country) REFERENCES MI182_rrlee.countries (id)
);