DROP TABLE MI182_RRLEE.PRESIDENTS;
DROP TABLE MI182_RRLEE.CITIES;
DROP TABLE MI182_RRLEE.COUNTRIES;
DROP TABLE MI182_RRLEE.DISTRICTS;
DROP TABLE MI182_RRLEE.HOUSE_NUMBERS;
DROP TABLE MI182_RRLEE.POSTAL_CODES;
DROP TABLE MI182_RRLEE.STREET_NAMES;
DROP TABLE MI182_RRLEE.UNIT_NUMBERS;
DROP TABLE MI182_RRLEE.PROVINCES;

DROP SEQUENCE MI182_RRLEE.UNIT_NUMBERS_SEQUENCE;
DROP TRIGGER MI182_RRLEE.UNIT_NUMBERS_TRIGGER;

DROP SEQUENCE MI182_RRLEE.HOUSE_NUMBERS_SEQUENCE;
DROP TRIGGER MI182_RRLEE.HOUSE_NUMBERS_TRIGGER;